# Generated by Django 3.0.2 on 2020-01-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuroData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=500)),
                ('date', models.CharField(blank=True, max_length=500)),
                ('doctor_id', models.CharField(blank=True, max_length=500)),
                ('doctors_note', models.CharField(blank=True, max_length=500)),
                ('lab_results', models.CharField(blank=True, max_length=500)),
                ('scan_results', models.CharField(blank=True, max_length=500)),
                ('neuro_sugery_details', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
