# Generated by Django 2.0.12 on 2020-04-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontointerface', '0002_userinputformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neurodata',
            name='date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='neurodata',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='neurodata',
            name='doctors_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='neurodata',
            name='lab_results',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='neurodata',
            name='neuro_sugery_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='neurodata',
            name='scan_results',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
