# Generated by Django 2.1.4 on 2020-08-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontointerface', '0003_auto_20200409_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=500)),
                ('date', models.CharField(blank=True, max_length=500, null=True)),
                ('doctor_id', models.CharField(blank=True, max_length=500, null=True)),
                ('doctors_note', models.CharField(blank=True, max_length=500, null=True)),
                ('lab_results', models.CharField(blank=True, max_length=500, null=True)),
                ('scan_results', models.CharField(blank=True, max_length=500, null=True)),
                ('neuro_sugery_details', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userinputformmodel',
            name='data_requested',
            field=models.CharField(choices=[('Neuraldata', 'NEURODATA'), ('Pediatricdata', 'PEDIATRIC DATA'), ('Gynaecdata', 'Gynac Data'), ('Cardio', 'CardioData')], default='Neuraldata', max_length=100),
        ),
    ]
