# Generated by Django 2.1.4 on 2020-08-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontointerface', '0004_auto_20200806_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='neurodata',
            name='hospital_name',
            field=models.CharField(blank=True, default='Hospital1', max_length=500, null=True),
        ),
    ]
